### ISSUE TITLE
Please update nuget dependencies to Lucene.NET 4.8.0 beta 6

### ISSUE THREAD

**Issue by zippy1981** [tomlm/Lucene.Net.Store.Azure#1]
I had a .NET Core 2.1 project (Azure Function specifically) that worked just fine with this and Lucnene .NET 4.8.0  beta5. When I updated my Lucene.NET references to beta 6, I got the following error:

> CS0012	The type 'Document' is defined in an assembly that is not referenced. You must add a reference to assembly 'Lucene.Net, Version=4.0.0.0, Culture=neutral, PublicKeyToken=null'.	Zippy1981.LuceneExample.Functions.Tests	C:\Users\Justin.Dearing\source\repos\Zippy1981.LuceneExample\Zippy1981.LuceneExample.Functions.Tests\Lucene\Models\DocumentExtensionsTests.cs	14	Active

I'll be posting the function service on github soon.

**Comment by jimp100** [comment]
Yes please to this too!

**Comment by tomlm** [comment]
I just uploaded updated to Lucene.Net 4.8.0 beta006
