### ISSUE TITLE
Support for paths

### ISSUE THREAD

**Issue by ManfredLange** [tomlm/Lucene.Net.Store.Azure#2]
At this stage an index using this package requires the index to be at in a container, e.g. `foo`. 

It would be great if the package would also support something like `foo\bar` where `foo` is the rootcontainer and `bar` would be the folder with the files of the index.

This would allow keeping multiple indexes in a single root container, e.g. `foo\red`, `foo\green`, `foo\blue` etc.

Note that with a previous AzureDirectory - from a different nuget package - this was possible. We'd love to use this package but this is a show stopper.

**Comment by ManfredLange** [comment]
All local tests and experiments going well I'm considering a PR.

**Comment by tomlm** [comment]
I just pushed v 4.8.0-beta006-2 which has this change.
new AzureDirectory("red/green/blue")
