### ISSUE TITLE
It Tooks Time to Connect With Azure

### ISSUE THREAD

**Issue by Mansoun** [tomlm/Lucene.Net.Store.Azure#20]
Hello. 
I have a problem. 
everything fines in details.
The problem is when want to create Writer or writer.Flush() .. it tooks time.. 7 seconds ...

The Diagnostic window in shows a bunch of Http request in one thread and it's kind of wierd ... 
Use Lucene.Net.Store.Azure 4.8.0-beta015

` string storageConString = _configuration["LuceneStorageConnectionString"];
            string folderName = _configuration["FolderNameLuceneIndex"];
            _azureDirectory = new AzureDirectory(_configuration["LuceneStorageConnectionString"]);
            this.writer = new IndexWriter(_azureDirectory, indexConfig);`

**Comment by tomlm** [comment]
This is normal. 

Lucene is pretty efficient at append only behavior for creating segment files, but at a certain configurable threshold it will merge files together creating multiple new segments. Each segment needs to be uploaded as a blob into azure, so depending on the size and quantity of new segments it is not at all unusual to have it be a "long" operation.

Best practice is to do all of your writing in one place and have the index searchers and readers be in a different place. While it may take a long time to upload the new segments, it in no way blocks the ability for other machines to access the old "snapshot". 

Second best practice is to create new index searchers on a background thread and then hot swap. That will ensure that the new index is fully downloaded before you start trying to search over it.
