### ISSUE TITLE
Doesn't work on Azure Storage Emulator v5.10

### ISSUE THREAD

**Issue by farlee2121** [tomlm/Lucene.Net.Store.Azure#5]
I am trying to develop locally using the Azure Storage Emulator (current stable version is v5.10).

However, after updating I get the error
`System.IndexOutOfRangeException: 'Index was outside the bounds of the array.'` from `FastTaxonomyFacetCounts`, 

This error does not happen with other directory types (`RAMDirectory` or `SimpleFSDirectory`).

Poking around I notice that the taxonomy directory is not empty, but the main index didn't end up with any data. 

This led me to try with a real blob container, which worked correctly. 

This seems to prove that the library doesn't work with storage emulator. Any ideas?

**Comment by tomlm** [comment]
which package are you using?  3.x or 4.x beta?

**Comment by farlee2121** [comment]
Ah. An important detail. I'm running the 4.8 beta. It worked when we were still on 3.x.

**Comment by farlee2121** [comment]
How can I help diagnose this error?

**Comment by tomlm** [comment]
I just uploaded v 4.8-3, which has updated azure storage library.  
It works fine against my azure storage emulator 5.10

**Comment by tomlm** [comment]
Actually, there is a new release of lucene, so I also just published 4.8.0-beta007

**Comment by farlee2121** [comment]
Update and tested. The latest version is working with storage emulator 5.10 for me. Thanks!
