### ISSUE TITLE
IndexSercher not Accepting azure Directory 

### ISSUE THREAD

**Issue by adolfie450** [tomlm/Lucene.Net.Store.Azure#8]
hi

I am trying to implement this, however, I seem to have run into a problem.  I have downgraded to the 4.8.0-beta011 and 011 builds of Lucene.Net and the other components.  

AzureDirectory azureDirectory = new AzureDirectory(endpoint);

IndexSearcher searcher = new IndexSearcher(azureDirectory); //

 indexSearcher is telling mere there is not overload for azureDirectory and is looking for indexReader, it an almost exact copy past from your example, I have gone through all the overloads and checked versions, it simply refuses to accept the azureDirectly. 

could you please advise when you have time, many thanks?

**Comment by tomlm** [comment]
The signature has changed in lucene.net beta
```
new IndexSearcher(DirectoryReader.Open(azureDirectory));
```
